[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup", "--cfg", "aes_armv8"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static", "--cfg", "aes_armv8"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["--cfg", "aes_armv8"]

[profile.release]
lto = true
